version: '2'

services:
    nginx-data:
        image: matthiasnoback/nginx-data
        container_name: nginx-data
        build:
            context: ./
            dockerfile: nginx-data/Dockerfile
        volumes:
            - /etc/nginx/certs
            - /etc/docker-gen/templates

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
        volumes_from:
            - nginx-data
        network_mode: bridge

    nginx-gen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes_from:
            - nginx
            - nginx-data
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        network_mode: bridge

    nginx-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-letsencrypt
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
            - nginx
            - nginx-data
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
        network_mode: bridge
